// <auto-generated />
using System;
using HRConnect.Server.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRConnect.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231021095026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BenefitDipendente", b =>
                {
                    b.Property<int>("BenefitsId")
                        .HasColumnType("int");

                    b.Property<int>("DipendentiId")
                        .HasColumnType("int");

                    b.HasKey("BenefitsId", "DipendentiId");

                    b.HasIndex("DipendentiId");

                    b.ToTable("BenefitDipendente");
                });

            modelBuilder.Entity("CandidatoHardSkill", b =>
                {
                    b.Property<int>("CandidatiId")
                        .HasColumnType("int");

                    b.Property<int>("HardSkillsId")
                        .HasColumnType("int");

                    b.HasKey("CandidatiId", "HardSkillsId");

                    b.HasIndex("HardSkillsId");

                    b.ToTable("CandidatoHardSkill");
                });

            modelBuilder.Entity("CandidatoSoftSkill", b =>
                {
                    b.Property<int>("CandidatiId")
                        .HasColumnType("int");

                    b.Property<int>("SoftSkillsId")
                        .HasColumnType("int");

                    b.HasKey("CandidatiId", "SoftSkillsId");

                    b.HasIndex("SoftSkillsId");

                    b.ToTable("CandidatoSoftSkill");
                });

            modelBuilder.Entity("DipendenteHardSkill", b =>
                {
                    b.Property<int>("DipendentiId")
                        .HasColumnType("int");

                    b.Property<int>("HardSkillsId")
                        .HasColumnType("int");

                    b.HasKey("DipendentiId", "HardSkillsId");

                    b.HasIndex("HardSkillsId");

                    b.ToTable("DipendenteHardSkill");
                });

            modelBuilder.Entity("DipendenteSoftSkill", b =>
                {
                    b.Property<int>("DipendentiId")
                        .HasColumnType("int");

                    b.Property<int>("SoftSkillsId")
                        .HasColumnType("int");

                    b.HasKey("DipendentiId", "SoftSkillsId");

                    b.HasIndex("SoftSkillsId");

                    b.ToTable("DipendenteSoftSkill");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CittaId")
                        .HasColumnType("int");

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComuneDiNascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContrattoId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentoID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaDiNascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatoDiNascita")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TitoloDiStudioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CittaId");

                    b.HasIndex("ContrattoId");

                    b.HasIndex("DocumentoID")
                        .IsUnique();

                    b.HasIndex("TitoloDiStudioId");

                    b.ToTable("Candidati");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Citta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SedeId");

                    b.ToTable("Citta");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Colloquio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatiID")
                        .HasColumnType("int");

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataColloquio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HRId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SedeId")
                        .HasColumnType("int");

                    b.Property<string>("Valutazione")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("HRId");

                    b.HasIndex("SedeId");

                    b.ToTable("Colloqui");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Contratto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<int?>("LivelloContrattualeID")
                        .HasColumnType("int");

                    b.Property<string>("TipoContratto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LivelloContrattualeID");

                    b.ToTable("Contratti");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Dipendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContrattoId")
                        .HasColumnType("int");

                    b.Property<int?>("LivelliContrattualiID")
                        .HasColumnType("int");

                    b.Property<int?>("MansioneId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContrattoId");

                    b.HasIndex("LivelliContrattualiID");

                    b.HasIndex("MansioneId");

                    b.HasIndex("SedeId");

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Documenti");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.EsperienzaLavorativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Azienda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int?>("ContrattoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MansioneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("ContrattoId");

                    b.HasIndex("MansioneId");

                    b.ToTable("EsperienzeLavorative");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.HR", b =>
                {
                    b.Property<int>("HRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HRId"));

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HRId");

                    b.ToTable("HRs");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.HardSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("TipologiaSkill")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HardSkills");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.LivelloContrattuale", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<int>("Livello")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("LivelliContrattuali");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Mansione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Mansioni");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Sede", b =>
                {
                    b.Property<int>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SedeId"));

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HRId")
                        .HasColumnType("int");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recapito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SedeId");

                    b.HasIndex("HRId")
                        .IsUnique();

                    b.ToTable("Sedi");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.SoftSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("TipologiaSkill")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SoftSkills");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.TitoloDiStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<string>("TipologiaTitolo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TitoliDiStudio");
                });

            modelBuilder.Entity("HardSkillLivelloContrattuale", b =>
                {
                    b.Property<int>("HardSkillsId")
                        .HasColumnType("int");

                    b.Property<int>("LivelliContrattualiID")
                        .HasColumnType("int");

                    b.HasKey("HardSkillsId", "LivelliContrattualiID");

                    b.HasIndex("LivelliContrattualiID");

                    b.ToTable("HardSkillLivelloContrattuale");
                });

            modelBuilder.Entity("LivelloContrattualeSoftSkill", b =>
                {
                    b.Property<int>("DescrizioneLavoriID")
                        .HasColumnType("int");

                    b.Property<int>("SoftSkillsId")
                        .HasColumnType("int");

                    b.HasKey("DescrizioneLavoriID", "SoftSkillsId");

                    b.HasIndex("SoftSkillsId");

                    b.ToTable("LivelloContrattualeSoftSkill");
                });

            modelBuilder.Entity("BenefitDipendente", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Benefit", null)
                        .WithMany()
                        .HasForeignKey("BenefitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Shared.Models.Dipendente", null)
                        .WithMany()
                        .HasForeignKey("DipendentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CandidatoHardSkill", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Candidato", null)
                        .WithMany()
                        .HasForeignKey("CandidatiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Shared.Models.HardSkill", null)
                        .WithMany()
                        .HasForeignKey("HardSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CandidatoSoftSkill", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Candidato", null)
                        .WithMany()
                        .HasForeignKey("CandidatiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Shared.Models.SoftSkill", null)
                        .WithMany()
                        .HasForeignKey("SoftSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DipendenteHardSkill", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Dipendente", null)
                        .WithMany()
                        .HasForeignKey("DipendentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Shared.Models.HardSkill", null)
                        .WithMany()
                        .HasForeignKey("HardSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DipendenteSoftSkill", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Dipendente", null)
                        .WithMany()
                        .HasForeignKey("DipendentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Shared.Models.SoftSkill", null)
                        .WithMany()
                        .HasForeignKey("SoftSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Candidato", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Citta", "Citta")
                        .WithMany()
                        .HasForeignKey("CittaId");

                    b.HasOne("HRConnect.Shared.Models.Contratto", null)
                        .WithMany("Candidato")
                        .HasForeignKey("ContrattoId");

                    b.HasOne("HRConnect.Shared.Models.Documento", "Documento")
                        .WithOne("Candidato")
                        .HasForeignKey("HRConnect.Shared.Models.Candidato", "DocumentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Shared.Models.TitoloDiStudio", null)
                        .WithMany("Candidati")
                        .HasForeignKey("TitoloDiStudioId");

                    b.Navigation("Citta");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Citta", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Colloquio", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Candidato", "Candidato")
                        .WithMany("Colloquio")
                        .HasForeignKey("CandidatoId");

                    b.HasOne("HRConnect.Shared.Models.HR", "HR")
                        .WithMany("Colloqui")
                        .HasForeignKey("HRId");

                    b.HasOne("HRConnect.Shared.Models.Sede", "Sede")
                        .WithMany("Colloqui")
                        .HasForeignKey("SedeId");

                    b.Navigation("Candidato");

                    b.Navigation("HR");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Contratto", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.LivelloContrattuale", "LivelloContrattuale")
                        .WithMany("Contratti")
                        .HasForeignKey("LivelloContrattualeID");

                    b.Navigation("LivelloContrattuale");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Dipendente", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Contratto", "Contratto")
                        .WithMany()
                        .HasForeignKey("ContrattoId");

                    b.HasOne("HRConnect.Shared.Models.LivelloContrattuale", "LivelliContrattuali")
                        .WithMany()
                        .HasForeignKey("LivelliContrattualiID");

                    b.HasOne("HRConnect.Shared.Models.Mansione", "Mansione")
                        .WithMany("Dipendenti")
                        .HasForeignKey("MansioneId");

                    b.HasOne("HRConnect.Shared.Models.Sede", "Sede")
                        .WithMany("Dipendenti")
                        .HasForeignKey("SedeId");

                    b.Navigation("Contratto");

                    b.Navigation("LivelliContrattuali");

                    b.Navigation("Mansione");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.EsperienzaLavorativa", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.Candidato", "Candidato")
                        .WithMany("EsperienzeLavorative")
                        .HasForeignKey("CandidatoId");

                    b.HasOne("HRConnect.Shared.Models.Contratto", "Contratto")
                        .WithMany()
                        .HasForeignKey("ContrattoId");

                    b.HasOne("HRConnect.Shared.Models.Mansione", "Mansione")
                        .WithMany()
                        .HasForeignKey("MansioneId");

                    b.Navigation("Candidato");

                    b.Navigation("Contratto");

                    b.Navigation("Mansione");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Sede", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.HR", "HR")
                        .WithOne("Sede")
                        .HasForeignKey("HRConnect.Shared.Models.Sede", "HRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HR");
                });

            modelBuilder.Entity("HardSkillLivelloContrattuale", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.HardSkill", null)
                        .WithMany()
                        .HasForeignKey("HardSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Shared.Models.LivelloContrattuale", null)
                        .WithMany()
                        .HasForeignKey("LivelliContrattualiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LivelloContrattualeSoftSkill", b =>
                {
                    b.HasOne("HRConnect.Shared.Models.LivelloContrattuale", null)
                        .WithMany()
                        .HasForeignKey("DescrizioneLavoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Shared.Models.SoftSkill", null)
                        .WithMany()
                        .HasForeignKey("SoftSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Candidato", b =>
                {
                    b.Navigation("Colloquio");

                    b.Navigation("EsperienzeLavorative");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Contratto", b =>
                {
                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Documento", b =>
                {
                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.HR", b =>
                {
                    b.Navigation("Colloqui");

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.LivelloContrattuale", b =>
                {
                    b.Navigation("Contratti");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Mansione", b =>
                {
                    b.Navigation("Dipendenti");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.Sede", b =>
                {
                    b.Navigation("Colloqui");

                    b.Navigation("Dipendenti");
                });

            modelBuilder.Entity("HRConnect.Shared.Models.TitoloDiStudio", b =>
                {
                    b.Navigation("Candidati");
                });
#pragma warning restore 612, 618
        }
    }
}
